services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:2.4
    container_name: monster_cms
    ports:
      - "9001:80"
    volumes:
      - .:/var/www/html/cms
    networks:
      - rx931

  db:
    image: mysql:5.7
    container_name: cms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rxninthr_monster
      # MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - rx931

networks:
  rx931:

volumes:
  dbdata:
